apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: message-queue
  name: message-queue
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: message-queue
    spec:
      containers:
      - image: vromero/activemq-artemis:2.6.2
        name: message-queue
        ports:
        - containerPort: 8161
        - containerPort: 61616
        env:
        - name: ARTEMIS_USERNAME
          value: admin
        - name: ARTEMIS_PASSWORD
          value: admin
      restartPolicy: Always
